---

- name: Create main.cf from template
  become: true
  template:
    dest: "{{ postfix_config }}/main.cf"
    src: main.cf.j2
    mode: 0644
    owner: root
    group: root
  notify: restart postfix

- name: Create master.cf file from template
  become: true
  template:
    dest: "{{ postfix_config }}/master.cf"
    src: master.cf.j2
    mode: 0644
    owner: root
    group: root
  notify: restart postfix

- name: Create postfix SASL maps for outbound authentication
  become: true
  template:
    dest: "{{ postfix_sasl_maps }}"
    src: sasl_maps.j2
    mode: 0600
    owner: root
    group: root
  notify: postmap sasl
  when: outbound_sasl_maps is defined

- name: Add root email alias
  become: true
  lineinfile:
    dest: /etc/aliases
    regexp: ^root
    line: "root: {{ root_alias }}"
  notify: newaliases
