---

- name: Install postfix and associated packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  when: '"apt" in ansible_pkg_mgr'
  loop: "{{ postfix_apt_pkgs }}"

- name: Install postfix mysql package
  become: true
  apt:
    name: postfix-mysql
    state: present
  when: '"apt" in ansible_pkg_mgr and mysql_generic[my_fqdn] is defined'

- name: Enable postfix service
  become: true
  service:
    name: postfix
    enabled: true
    state: started
