---

- name: Install Spamassassin packages
  become: true
  package:
    name:
      - sa-compile
      - spamassassin
      - spamc
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Create Spamassassin configuration file
  become: true
  copy:
    src: local.cf
    dest: /etc/spamassassin/local.cf
    owner: root
    group: root
    mode: 0644
  notify: restart spamassassin debian

- name: Ensure Spamassasin service is started
  become: true
  service:
    name: "{{ debian_spamassassin_service }}"
    state: started
    enabled: true
  when: ansible_distribution == 'Debian'

