---
# handlers file for postfix-destination

- name: restart postfix
  become: true
  service:
    name: postfix
    state: restarted

- name: restart spamassassin
  become: true
  service:
    name: spamassassin
    state: restarted

- name: postmap sasl
  become: true
  shell: "postmap {{ postfix_sasl_maps }}"

- name: postmap generic
  become: true
  shell: "postmap {{ postfix_generic_maps }}"

- name: newaliases
  become: true
  shell: "newaliases"
